layout_spectrum: 0.2443609
color:
  saturation: 0.4269641
  lightness: 0.5835342
  brandStrength: 0.08039133
  brandColors:
    - '#FFFFFF'
    - '#6D6D6F'
    - '#C6C6C7'
  rhythmicContrast: 0.6766706
typography_spectrum: 0.3066595
name: Reliable Window Cleaning
